version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: procaptcha
      WORDPRESS_DB_PASSWORD: procaptchapass
      WORDPRESS_DB_NAME: procaptchadb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: procaptchadb
      MYSQL_USER: procaptcha
      MYSQL_PASSWORD: procaptchapass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
